# encoding: UTF-8

require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BookkeepingsController do

  # This should return the minimal set of attributes required to create a valid
  # Bookkeeping. As you add validations to Bookkeeping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "issue_date" => "2013-10-07" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookkeepingsController. Be sure to keep this updated too.
  let(:valid_session) { {} } 

  describe "GET index" do
    it "assigns all bookkeepings as @bookkeepings" do
      bookkeeping = Bookkeeping.create! attributes_for :bookkeeping
      get :index, {}, valid_session
      expect(assigns(:bookkeepings)).to eq([bookkeeping])
    end
  end

  describe "GET #show 액션" do
    it "assigns the requested bookkeeping as @bookkeeping" do
      group = create(:group)
      bookkeeping = group.bookkeepings.first
      get :show, {:group_id => group, :id => bookkeeping}
      expect(assigns(:bookkeeping)).to eq bookkeeping
      # bookkeeping = Bookkeeping.create! valid_attributes
      # get :show, {:id => bookkeeping.to_param}, valid_session
      # assigns(:bookkeeping).should eq(bookkeeping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bookkeeping" do
        expect {
          post :create, {:bookkeeping => valid_attributes}, valid_session
        }.to change(Bookkeeping, :count).by(1)
      end

      it "assigns a newly created bookkeeping as @bookkeeping" do
        post :create, {:bookkeeping => valid_attributes}, valid_session
        assigns(:bookkeeping).should be_a(Bookkeeping)
        assigns(:bookkeeping).should be_persisted
      end

      it "redirects to the created bookkeeping" do
        post :create, {:bookkeeping => valid_attributes}, valid_session
        response.should redirect_to(Bookkeeping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bookkeeping as @bookkeeping" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bookkeeping.any_instance.stub(:save).and_return(false)
        post :create, {:bookkeeping => { "issue_date" => "invalid value" }}, valid_session
        assigns(:bookkeeping).should be_a_new(Bookkeeping)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bookkeeping.any_instance.stub(:save).and_return(false)
        post :create, {:bookkeeping => { "issue_date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bookkeeping" do
        bookkeeping = Bookkeeping.create! valid_attributes
        # Assuming there are no other bookkeepings in the database, this
        # specifies that the Bookkeeping created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bookkeeping.any_instance.should_receive(:update).with({ "issue_date" => "2013-10-07" })
        put :update, {:id => bookkeeping.to_param, :bookkeeping => { "issue_date" => "2013-10-07" }}, valid_session
      end

      it "assigns the requested bookkeeping as @bookkeeping" do
        bookkeeping = Bookkeeping.create! valid_attributes
        put :update, {:id => bookkeeping.to_param, :bookkeeping => valid_attributes}, valid_session
        assigns(:bookkeeping).should eq(bookkeeping)
      end

      it "redirects to the bookkeeping" do
        bookkeeping = Bookkeeping.create! valid_attributes
        put :update, {:id => bookkeeping.to_param, :bookkeeping => valid_attributes}, valid_session
        response.should redirect_to(bookkeeping)
      end
    end

    describe "with invalid params" do
      it "assigns the bookkeeping as @bookkeeping" do
        bookkeeping = Bookkeeping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bookkeeping.any_instance.stub(:save).and_return(false)
        put :update, {:id => bookkeeping.to_param, :bookkeeping => { "issue_date" => "invalid value" }}, valid_session
        assigns(:bookkeeping).should eq(bookkeeping)
      end

      it "re-renders the 'edit' template" do
        bookkeeping = Bookkeeping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bookkeeping.any_instance.stub(:save).and_return(false)
        put :update, {:id => bookkeeping.to_param, :bookkeeping => { "issue_date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bookkeeping" do
      bookkeeping = Bookkeeping.create! valid_attributes
      expect {
        delete :destroy, {:id => bookkeeping.to_param}, valid_session
      }.to change(Bookkeeping, :count).by(-1)
    end

    it "redirects to the bookkeepings list" do
      bookkeeping = Bookkeeping.create! valid_attributes
      delete :destroy, {:id => bookkeeping.to_param}, valid_session
      response.should redirect_to(bookkeepings_url)
    end
  end

end
