require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MonthlyBalancesController do

  # This should return the minimal set of attributes required to create a valid
  # MonthlyBalance. As you add validations to MonthlyBalance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "group" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MonthlyBalancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all monthly_balances as @monthly_balances" do
      monthly_balance = MonthlyBalance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:monthly_balances).should eq([monthly_balance])
    end
  end

  describe "GET show" do
    it "assigns the requested monthly_balance as @monthly_balance" do
      monthly_balance = MonthlyBalance.create! valid_attributes
      get :show, {:id => monthly_balance.to_param}, valid_session
      assigns(:monthly_balance).should eq(monthly_balance)
    end
  end

  describe "GET new" do
    it "assigns a new monthly_balance as @monthly_balance" do
      get :new, {}, valid_session
      assigns(:monthly_balance).should be_a_new(MonthlyBalance)
    end
  end

  describe "GET edit" do
    it "assigns the requested monthly_balance as @monthly_balance" do
      monthly_balance = MonthlyBalance.create! valid_attributes
      get :edit, {:id => monthly_balance.to_param}, valid_session
      assigns(:monthly_balance).should eq(monthly_balance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MonthlyBalance" do
        expect {
          post :create, {:monthly_balance => valid_attributes}, valid_session
        }.to change(MonthlyBalance, :count).by(1)
      end

      it "assigns a newly created monthly_balance as @monthly_balance" do
        post :create, {:monthly_balance => valid_attributes}, valid_session
        assigns(:monthly_balance).should be_a(MonthlyBalance)
        assigns(:monthly_balance).should be_persisted
      end

      it "redirects to the created monthly_balance" do
        post :create, {:monthly_balance => valid_attributes}, valid_session
        response.should redirect_to(MonthlyBalance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved monthly_balance as @monthly_balance" do
        # Trigger the behavior that occurs when invalid params are submitted
        MonthlyBalance.any_instance.stub(:save).and_return(false)
        post :create, {:monthly_balance => { "group" => "invalid value" }}, valid_session
        assigns(:monthly_balance).should be_a_new(MonthlyBalance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MonthlyBalance.any_instance.stub(:save).and_return(false)
        post :create, {:monthly_balance => { "group" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested monthly_balance" do
        monthly_balance = MonthlyBalance.create! valid_attributes
        # Assuming there are no other monthly_balances in the database, this
        # specifies that the MonthlyBalance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MonthlyBalance.any_instance.should_receive(:update).with({ "group" => "" })
        put :update, {:id => monthly_balance.to_param, :monthly_balance => { "group" => "" }}, valid_session
      end

      it "assigns the requested monthly_balance as @monthly_balance" do
        monthly_balance = MonthlyBalance.create! valid_attributes
        put :update, {:id => monthly_balance.to_param, :monthly_balance => valid_attributes}, valid_session
        assigns(:monthly_balance).should eq(monthly_balance)
      end

      it "redirects to the monthly_balance" do
        monthly_balance = MonthlyBalance.create! valid_attributes
        put :update, {:id => monthly_balance.to_param, :monthly_balance => valid_attributes}, valid_session
        response.should redirect_to(monthly_balance)
      end
    end

    describe "with invalid params" do
      it "assigns the monthly_balance as @monthly_balance" do
        monthly_balance = MonthlyBalance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MonthlyBalance.any_instance.stub(:save).and_return(false)
        put :update, {:id => monthly_balance.to_param, :monthly_balance => { "group" => "invalid value" }}, valid_session
        assigns(:monthly_balance).should eq(monthly_balance)
      end

      it "re-renders the 'edit' template" do
        monthly_balance = MonthlyBalance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MonthlyBalance.any_instance.stub(:save).and_return(false)
        put :update, {:id => monthly_balance.to_param, :monthly_balance => { "group" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested monthly_balance" do
      monthly_balance = MonthlyBalance.create! valid_attributes
      expect {
        delete :destroy, {:id => monthly_balance.to_param}, valid_session
      }.to change(MonthlyBalance, :count).by(-1)
    end

    it "redirects to the monthly_balances list" do
      monthly_balance = MonthlyBalance.create! valid_attributes
      delete :destroy, {:id => monthly_balance.to_param}, valid_session
      response.should redirect_to(monthly_balances_url)
    end
  end

end
